/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  getStarted: [{ type: "autogenerated", dirName: "get-started" }],
  flutter: [{ type: "autogenerated", dirName: "sdk/flutter" }],
  kotlin: [{ type: "autogenerated", dirName: "sdk/kotlin" }],

  studio: [
    {
      type: "doc",
      label: "Get Started",
      id: "studio/index",
    },
    { type: "doc", id: "release-notes/index" },
  ],
  releaseNotes: [
    {
      type: "doc",
      label: "Release Notes",
      id: "release-notes/index",
    },
  ],
};

module.exports = sidebars;
